/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fastfoodcompany.clientes.vistas;

import fastfoodcompany.clientes.acciones.AccionesAltaClientes;
import fastfoodcompany.principal.FastFoodCompanyFrame;

/**
 *
 * @author Fabio
 */
public class PanelAltaClientes extends javax.swing.JPanel {

    private FastFoodCompanyFrame frame;
    private AccionesAltaClientes acciones;
    /**
     * Creates new form PanelAltaClientes
     */
    public PanelAltaClientes(FastFoodCompanyFrame frame){
        this.frame = frame;
        this.acciones = new AccionesAltaClientes(this);
        initComponents();
        
       cambiarEstadoLblValorNoCorrecto(false);
    }
    
    public FastFoodCompanyFrame getFrame(){
        return frame;
    }
    
    public void setFrame(FastFoodCompanyFrame frame){
        this.frame = frame;
    }
    
    /**
     * Una vez completado el guardado del cliente, se eliminaran los valores
     * para poder añadir otro cliente nuevo
     */
    public void borraVariables(){
        txtApellido1.setText("");
        txtApellido2.setText("");
        txtNombre.setText("");
        cambiarEstadoLblValorNoCorrecto(false);
    }
    
    public void cambiarEstadoLblValorNoCorrecto(boolean state){
         lblValorNoCorrecto.setVisible(state);
    }
    
    
    /*
    Setters and getters
    */
    public javax.swing.JTextField getTxtApellido1(){
        return txtApellido1;
    }
    public javax.swing.JTextField getTxtApellido2(){
        return txtApellido2;
    }
    public javax.swing.JTextField getTxtNombre(){
        return txtNombre;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNombre = new javax.swing.JLabel();
        lblApellido1 = new javax.swing.JLabel();
        lblApellido2 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtApellido1 = new javax.swing.JTextField();
        txtApellido2 = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        lblValorNoCorrecto = new javax.swing.JLabel();

        setLayout(null);

        lblNombre.setText("Nombre");
        add(lblNombre);
        lblNombre.setBounds(30, 30, 80, 14);

        lblApellido1.setText("Apellido 1");
        add(lblApellido1);
        lblApellido1.setBounds(30, 70, 80, 14);

        lblApellido2.setText("Apellido 2");
        add(lblApellido2);
        lblApellido2.setBounds(30, 110, 80, 14);

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        add(txtNombre);
        txtNombre.setBounds(130, 30, 110, 18);

        txtApellido1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellido1ActionPerformed(evt);
            }
        });
        add(txtApellido1);
        txtApellido1.setBounds(130, 70, 110, 18);

        txtApellido2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellido2ActionPerformed(evt);
            }
        });
        add(txtApellido2);
        txtApellido2.setBounds(130, 110, 110, 18);

        btnGuardar.setText("Guardar");
        btnGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGuardarMouseClicked(evt);
            }
        });
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        add(btnGuardar);
        btnGuardar.setBounds(140, 180, 100, 24);

        lblValorNoCorrecto.setForeground(new java.awt.Color(255, 0, 51));
        lblValorNoCorrecto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblValorNoCorrecto.setText("Algun valor no es válido");
        lblValorNoCorrecto.setToolTipText("Revisa los valores introducidos y vuelve a probarlo");
        add(lblValorNoCorrecto);
        lblValorNoCorrecto.setBounds(30, 150, 210, 14);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtApellido1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellido1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellido1ActionPerformed

    private void txtApellido2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellido2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellido2ActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnGuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarMouseClicked
        // TODO add your handling code here:
        acciones.guardarCliente();
    }//GEN-LAST:event_btnGuardarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JLabel lblApellido1;
    private javax.swing.JLabel lblApellido2;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblValorNoCorrecto;
    private javax.swing.JTextField txtApellido1;
    private javax.swing.JTextField txtApellido2;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
