/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fastfoodcompany.clientes.vistas;

import fastfoodcompany.clientes.acciones.AccionesBajaCliente;
import fastfoodcompany.principal.FastFoodCompanyFrame;

/**
 *
 * @author fabio
 */
public class PanelBajaCliente extends javax.swing.JPanel {
    FastFoodCompanyFrame frame;
    /**
     * Creates new form PanelBajaCliente
     */
    public PanelBajaCliente(FastFoodCompanyFrame frame) {
        initComponents();
        this.frame = frame;
        estadoLblNoValor(false);
    }
    
    
    /**
     * Al borrar un cliente, la variable numeroCliente se resetea por si se desea
     * eliminar a mas de uno
     */
    public void borraVariables(){
        txtNumeroCliente.setText("");
        estadoLblNoValor(false);
    }
    
    public void estadoLblNoValor(boolean state){
        lblNoValor.setVisible(state);
    }
    
    //Getters
    
    public javax.swing.JTextField getTxtNumeroCliente(){
        return txtNumeroCliente;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGuardar = new javax.swing.JButton();
        lblNumeroCliente = new javax.swing.JLabel();
        txtNumeroCliente = new javax.swing.JTextField();
        lblNoValor = new javax.swing.JLabel();

        setLayout(null);

        btnGuardar.setText("Eliminar");
        btnGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnGuardarMousePressed(evt);
            }
        });
        add(btnGuardar);
        btnGuardar.setBounds(220, 100, 100, 24);

        lblNumeroCliente.setText("Número del cliente a eliminar:");
        add(lblNumeroCliente);
        lblNumeroCliente.setBounds(30, 40, 221, 14);

        txtNumeroCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeroClienteActionPerformed(evt);
            }
        });
        add(txtNumeroCliente);
        txtNumeroCliente.setBounds(260, 40, 60, 18);

        lblNoValor.setForeground(new java.awt.Color(255, 0, 0));
        lblNoValor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNoValor.setText("El número de cliente no es válido");
        lblNoValor.setToolTipText("Comprueba el número de los clientes en la Lista");
        add(lblNoValor);
        lblNoValor.setBounds(30, 70, 293, 14);
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarMousePressed
        // TODO add your handling code here:
        AccionesBajaCliente accionesBajaCliente = new AccionesBajaCliente(this);
        accionesBajaCliente.bajaCliente();
        
    }//GEN-LAST:event_btnGuardarMousePressed

    private void txtNumeroClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroClienteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JLabel lblNoValor;
    private javax.swing.JLabel lblNumeroCliente;
    private javax.swing.JTextField txtNumeroCliente;
    // End of variables declaration//GEN-END:variables
}
