/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fastfoodcompany.clientes.vistas;

import fastfoodcompany.clientes.acciones.AccionesListaClientes;
import fastfoodcompany.principal.FastFoodCompanyFrame;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author fabio
 */
public class PanelListaClientes extends javax.swing.JPanel {

    private FastFoodCompanyFrame frame;
    private DefaultTableModel tabla;
    
    /**
     * Creates new form PanelListaClientes
     */
    public PanelListaClientes(FastFoodCompanyFrame frame) {
        initComponents();
        this.frame = frame;
        cargaTabla();
        inizializaLista();
    }
    
    /**
     * Accedemos a la clase accionesDB para que nos escriva en nuestra tabla
     * todos los clientes que tenemos creados y guardados
     */
    private void inizializaLista(){
        AccionesListaClientes accionesDB = new AccionesListaClientes(tabla);
        accionesDB.listaClientesGuardados();
    }
    
    /**
     * Cargamos una tabla con los parametros que deseamos
     */
    public void cargaTabla(){
        tabla = new DefaultTableModel(new String[]{
            "Numero Cliente", "Nombre", "P Apellido", "S Apellido"
        }, 0);
        
        tblClientes.setModel(tabla);        
    }
    
    
    /**
     * Acceso a los componentes
     */
    
    public DefaultTableModel getTabla(){
        return tabla;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblClientes = new javax.swing.JTable();

        setLayout(new java.awt.GridLayout(1, 0));

        tblClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Numero de cliente", "Nombre", "Apellido 1", "Apellido 2"
            }
        ));
        tblClientes.setRowHeight(20);
        tblClientes.setRowMargin(5);
        jScrollPane1.setViewportView(tblClientes);

        add(jScrollPane1);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblClientes;
    // End of variables declaration//GEN-END:variables
}
